name: phinex
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_screenutil: 4.0.2+3
  steps_indicator:
  font_awesome_flutter: ^8.10.0
  date_time_format: 1.1.0
  provider:
  bubble: ^1.1.9+1
  cupertino_icons: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  chips_choice: ^2.0.1
  fluttertoast: 4.0.1
  country_picker: 1.1.2
  dio: ^3.0.8
  rxdart: ^0.23.1
  shared_preferences: ^0.5.12+4
  carousel_slider:
  cached_network_image: ^2.3.3
  flutter_range_slider: ^1.5.0
  multi_image_picker: ^4.7.14
  permission_handler: 4.4.0+hotfix.2
  flare_flutter:
  flutter_absolute_path: ^1.0.6
  weekday_selector: 0.4.0
  pusher_websocket_flutter: ^0.2.0
  dotted_border:
  emoji_picker: ^0.1.0
  image_picker: ^0.6.7+15
  currency_picker: ^1.0.4
  badges: ^1.1.6
  expandable: ^4.1.4
  flutter_svg:
  after_init: ^0.1.2
  page_transition: ^1.1.7+3
  time_ago_provider:
  chewie: 0.12.0
  video_player: ^1.0.1
  url_launcher: ^5.7.10
  connectivity:
  country_pickers: ^1.3.0
  numeral: ^1.0.4
  photo_view: ^0.10.3
  language_pickers: ^0.2.0+1
  flutter_launcher_icons: ^0.8.1
  flutter_html:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^0.1.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - assets/flare/
    - assets/styles/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf